### ISSUE TITLE
OS Failure - not so failure

### ISSUE THREAD

**Issue by warthog9** [tenstorrent/tt-smi#2]
Right now if the OS isn't Ubuntu 20.04, tt-smi reports a failure.  This isn't EXACTLY a failure, more a warning that it's not supported / untested.  This should likely get moved to softer language of "Warning - OS not supported" or something similar.

**Comment by sbansalTT** [comment]
Fixed in release [tt_tools_common 1.1.0](https://github.com/tenstorrent/tt-tools-common/blob/main/CHANGELOG.md#110---21022024)
