### ISSUE TITLE
Firmware version shown per device does not show bundle version causing confusion

### ISSUE THREAD

**Issue by warthog9** [tenstorrent/tt-smi#23]
Generally we only refer to the firmware versions by the bundle version we are shipping, which works fine - except when on the tab showing the versions for the card, it shows the firmware version itself, not the bundle version and since we never refer to the separate firmware version anywhere it can lead to confusion on what is/isn't installed.  Please add a column for bundle version as well

**Comment by sbansalTT** [comment]
Updated as of 2.2.3 - Added fw bundle column to firmware table
<img width="898" alt="image" src="https://github.com/user-attachments/assets/4d067b86-5b7b-470e-a41d-2e4ba9997ba7">
