### ISSUE TITLE
TT-SMI textual breaks when moving the cursor too fast

### ISSUE THREAD

**Issue by hmohiuddinTT** [tenstorrent/tt-smi#24]
A customer is reporting an issue that breaks tt-smi when moving the cursor too fast: 

<img width="771" alt="image" src="https://github.com/tenstorrent/tt-smi/assets/124714595/29a76f49-c7eb-4bec-8323-5874344a2138">

Probably a bug with textual? Let's see if there's any mention of it on the textual repo, or if there's a newer version of textual we can upgrade to.

Need to figure out how to repro this issue as well.

**Comment by sbansalTT** [comment]
Hey Hammad, textual version has been bumped from 0.43.0 to 0.59.0 as of [v2.2.1](https://github.com/tenstorrent/tt-smi/commit/5fdfcea2afcb08ec8abfdca9b567b248eaeb647b)
Could you try it on your end and see if it fixes your issue?

**Comment by warthog9** [comment]
since we haven't heard back on if this did/did not fix it, going to assume it's no longer an issue as we were never able to reproduce.  If it comes back up, reopen or file a new bug and we'll take another go at it.
