### ISSUE TITLE
Migrate from jsons library

### ISSUE THREAD

**Issue by warthog9** [tenstorrent/tt-smi#33]
jsons has served us well, but it isn't in the distro packaging by default and there's some concern about it being maintained going forward (as of this writing it hasn't been committed to in 2 years).

Lets go ahead and swap that out for a more expected json library

**Comment by knauth** [comment]
Done as of [387faff](https://github.com/knauth/tt-smi/commit/387faffbf96f303de2dc26c025d99026adf90e5b).
