### ISSUE TITLE
Firmware not found

### ISSUE THREAD

**Issue by satishwagh** [tenstorrent/tt-smi#34]
Followed the installation steps for latest tt-smi version 3.0.0 on Ubuntu-22.04. No error/warning while installation but gets the following error when I try to run the command `tt-smi`

Detected Chips: 1
 Detecting ARC: /
 Detecting DRAM: /
 [] ETH: /
Gathering Information ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/home/user/2.2.3/.venv/bin/tt-smi", line 8, in <module>
    sys.exit(main())
  File "/home/user/2.2.3/.venv/lib/python3.10/site-packages/tt_smi/tt_smi.py", line 788, in main
    backend = TTSMIBackend(devices)
  File "/home/user/2.2.3/.venv/lib/python3.10/site-packages/tt_smi/tt_smi_backend.py", line 79, in _init_
    self.smbus_telem_info.append(self.get_smbus_board_info(i))
  File "/home/user/2.2.3/.venv/lib/python3.10/site-packages/tt_smi/tt_smi_backend.py", line 173, in get_smbus_board_info
    telem_struct = pylewen_chip.get_telemetry()
**Exception: Unsupported fw version, got 1010000 but required 1040000**

I degraded the tt-smi from 3.0.0 to 2.2.3 but still same error. Please note that above message is copied from 2.2.3 output.

I wonder, which firmware needs to be updated?

**Comment by sbansalTT** [comment]
Hey Satish, thanks for the issue - could you tell me which generation of board you currently have? 
If its a GS or WH board then you can follow the steps in tt-flash to update all the firmwares to the right versions and then smi should run. 
Link for tt-flash - https://github.com/tenstorrent/tt-flash
Link for downloading fw bundle -  https://github.com/tenstorrent/tt-firmware
