### ISSUE TITLE
Add support for snapshot to stdout

### ISSUE THREAD

**Issue by ihamer-tt** [tenstorrent/tt-smi#39]
It seems that we cannot use -s to just print out the information to stdout. This would be useful when coupled with other linux tools (such as grep. It should probably be the default. For example:

- `-s` print to stdout
- `-f file.json` save to file.json
- `-f` autogenerate the filename and save

**Comment by tt-rkim** [comment]
An alternative is to immediately cat the file and use `jq` to parse JSON as an unblocker

**Comment by TTDRosen** [comment]
@sbansalTT the intended workaround of `tt-smi -s -f /dev/stdout | jq` does not appear to work here. We might also want to consider making the print to stdout the default behaviour and let -f specify a file.

**Comment by knauth** [comment]
Resolved by #59.
