### ISSUE TITLE
Allow specifying target filename for JSON config output

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-smi#6]
Right now, when using `-s`, it outputs a JSON with a pre-determined filename, appending a date.

This is not super great for automation. Could we have the ability to set a snapshot name just like the old SMI?

**Comment by sbansalTT** [comment]
Hey Raymond, we have it already added that feature in, you have to use the `-f` flag to set the filename of the snapshot, exactly like old SMI. Link to instructions - https://github.com/tenstorrent/tt-smi?tab=readme-ov-file#snapshots

**Comment by tt-rkim** [comment]
Hey @sbansalTT - I mean with the `-g` option, not the `-s` option.

For example, here, it would be nice if the first one generated `log.log` instead of a pre-determined JSON filename.

<img width="681" alt="Screen Shot 2024-02-21 at 11 35 42 AM" src="https://github.com/tenstorrent/tt-smi/assets/109366641/0e998a29-3db9-4830-bc92-2df9caedda1b">

**Comment by sbansalTT** [comment]
Oh gotcha - yes, I will add that into the next release

**Comment by sbansalTT** [comment]
This has been fixed as of release 2.1.0
you should now be able to specify the file, or use the default with -g when generating the reset config
