### ISSUE TITLE
tt-smi AICLK fixed on maximum freq

### ISSUE THREAD

**Issue by Dobob1022** [tenstorrent/tt-smi#7]
After running the demo code on grayskull, TT-SMI Said 
```AICLK(MHZ)
  1202/1202
```
the demo was ended but it's still fixed on 1202MHz. 

But I think it's temporary issue, Because After restart tt-smi it's shown as like normal. 

![Screenshot 2024-02-28 at 1 34 50 PM](https://github.com/tenstorrent/tt-smi/assets/20010553/5137c213-5d19-42b8-b4f1-5f6a91193aac)

**Comment by sbansalTT** [comment]
Hey, could you try again with the latest FW and latest SMI - improvements have been made and it would be helpful to see if it can be reproduced on the latest changes

**Comment by warthog9** [comment]
This is probably related to tenstorrent/luwen#4

**Comment by milank94** [comment]
@Dobob1022 following up to see if this is still an issue you are experiencing. Has the above guidance been helpful?

**Comment by Dobob1022** [comment]
Sorry For Late reply, The firmware update and latest tt-smi can display like normal

**Comment by sbansalTT** [comment]
Thanks! closing issue
